# Generated by Django 4.2.3 on 2023-08-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='numbers',
        ),
    ]
